// Generated by CoffeeScript 1.8.0
(function() {
  window.display_maze_defaults = function(container_id) {
    var container, map, map_input, maze_map, maze_map_container, row, x, _i, _j, _results;
    container = $(container_id);
    maze_map = [];
    maze_map_container = [];
    row = $("<div>");
    row.attr("class", "row");
    for (x = _i = 0; _i < 6; x = _i += 1) {
      maze_map_container = $("<div>");
      maze_map_container.attr("id", "mazebuilder_map0" + x);
      maze_map_container.attr("onclick", "javascript:select_maze('#mazebuilder_map0" + x + "')");
      maze_map_container.attr("class", "col-xs-4");
      if (x % 3 === 0) {
        container.append(row);
        row = $("<div>");
        row.attr("class", "row first-row");
      }
      row.append(maze_map_container);
    }
    container.append(row);
    _results = [];
    for (x = _j = 0; _j < 6; x = _j += 1) {
      maze_map[x] = new Maze("#mazebuilder_map0" + x, 5, 5, true);
      maze_map[x].create();
      map = maze_map[x].random_map();
      map_input = $("<input>");
      map_input.attr("type", "hidden");
      map_input.attr("value", "[" + map + "]");
      _results.push($("#mazebuilder_map0" + x).append(map_input));
    }
    return _results;
  };

  window.display_maze = function() {
    var maze_map, touch_tracker;
    window.maze = new Maze("#mazebuilder", 5, 5, false);
    window.maze_canvas = maze.create();
    maze_map = $("#mazebuilder_map");
    maze_map.val("[" + maze.map + "]");
    touch_tracker = new TouchTracker(maze_canvas, {
      swipeThreshold: 400
    });
    return maze_canvas.on("click", function(event) {
      maze.toggle_cell(event);
      return maze_map.val("[" + maze.map + "]");
    });
  };

  window.select_maze = function(map_container_id) {
    var map;
    map = $(map_container_id + " input").val();
    return maze.load_map(map);
  };

}).call(this);
